# Generated by Django 2.1.2 on 2018-10-30 07:33

from django.db import migrations, models
import djongo.models.fields
import test_djongo.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tagline', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog', djongo.models.fields.EmbeddedModelField(model_container=test_djongo.models.Blog, null=True)),
                ('meta_data', djongo.models.fields.EmbeddedModelField(model_container=test_djongo.models.MetaData, null=True)),
                ('headline', models.CharField(max_length=255)),
                ('body_text', models.TextField()),
                ('authors', djongo.models.fields.ArrayModelField(model_container=test_djongo.models.Author)),
                ('n_comments', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MetaData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_pingbacks', models.IntegerField()),
                ('rating', models.IntegerField()),
            ],
        ),
    ]
