# Generated by Django 2.2.2 on 2020-03-19 09:54

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comic_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='normal', max_length=10)),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('book_id', models.IntegerField(default=0, verbose_name='小说ID')),
                ('title', models.CharField(default='', max_length=60, verbose_name='章节标题')),
                ('content', models.CharField(default='', max_length=10000, verbose_name='章节内容')),
                ('number', models.IntegerField(default=0, verbose_name='章节编号')),
                ('order', models.IntegerField(default=0, verbose_name='排序位置')),
                ('active', models.BooleanField(default=True, verbose_name='生效')),
                ('origin_addr', models.CharField(default='', max_length=200, verbose_name='原始地址')),
            ],
            options={
                'verbose_name_plural': '章节',
                'db_table': 'book_chapter',
                'ordering': ['order', '-update_at'],
                'permissions': (('book_chapter_add', '添加小说章节'), ('book_chapter_edit', '编辑小说章节'), ('book_chapter_detail', '查看小说章节'), ('book_chapter_delete', '删除小说章节')),
            },
            managers=[
                ('normal', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='normal', max_length=10)),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.CharField(default='', max_length=60, unique=True, verbose_name='小说名称')),
                ('collection_num', models.IntegerField(default=0, null=True, verbose_name='收藏数量')),
                ('click_num', models.IntegerField(default=0, null=True, verbose_name='点击数量')),
                ('desc', models.CharField(default='', max_length=500, verbose_name='描述')),
                ('markup', models.CharField(default='', max_length=100, null=True, verbose_name='标签')),
                ('on_shelf', models.BooleanField(default=True, verbose_name='是否上架')),
                ('is_finished', models.BooleanField(default=False, verbose_name='是否能已完结')),
                ('latest_chapter', models.CharField(default='', max_length=20, verbose_name='最新章节')),
                ('origin_addr', models.CharField(default='', max_length=200, verbose_name='原始地址')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='comic_admin.Author')),
            ],
            options={
                'verbose_name_plural': '小说',
                'db_table': 'book',
                'ordering': ['-update_at'],
                'permissions': (('book_add', '添加小说'), ('book_edit', '编辑小说'), ('book_detail', '查看小说'), ('book_delete', '删除小说')),
            },
            managers=[
                ('normal', django.db.models.manager.Manager()),
            ],
        ),
    ]
