# Generated by Django 3.0.4 on 2020-03-14 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberviewhistory',
            name='chapter_title',
            field=models.CharField(default='', max_length=50, verbose_name='章节主题'),
        ),
        migrations.AlterField(
            model_name='memberviewhistory',
            name='data_type',
            field=models.CharField(choices=[('BOOK', '小说'), ('COMIC', '漫画')], default='BOOK', max_length=50, verbose_name='数据类型'),
        ),
        migrations.AlterField(
            model_name='task',
            name='markup',
            field=models.CharField(default='', max_length=200, verbose_name='任务备注'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_status',
            field=models.CharField(choices=[('WAIT', '等待执行'), ('RUNNING', '执行中'), ('FINISH', '执行结束'), ('FAILD', '执行失败')], default='WAIT', max_length=50, verbose_name='任务状态'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('BOOK_INSERT', '新增小说'), ('BOOK_CHAPTER_UPDATE', '更新小说章节'), ('COMIC_INSERT', '新增漫画'), ('COMIC_CHAPTER_UPDATE', '更新漫画章节')], default='BOOK_INSERT', max_length=50, verbose_name='任务类型'),
        ),
    ]
