# Generated by Django 2.2.2 on 2020-03-19 09:54

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='normal', max_length=10)),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(default='anonymous', max_length=60, verbose_name='作者名')),
                ('gender', models.CharField(choices=[('M', '男'), ('F', '女'), ('A', '未知')], default='A', max_length=2, verbose_name='性别')),
                ('mobile_phone', models.CharField(default='', max_length=20, verbose_name='手机号')),
            ],
            options={
                'verbose_name_plural': '作者',
            },
            managers=[
                ('normal', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='normal', max_length=10)),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('comic_id', models.IntegerField(default=0, verbose_name='漫画ID')),
                ('title', models.CharField(default='', max_length=60, verbose_name='章节标题')),
                ('number', models.IntegerField(default=0, verbose_name='章节编号')),
                ('order', models.IntegerField(default=0, verbose_name='排序位置')),
                ('active', models.BooleanField(default=True, verbose_name='生效')),
                ('origin_addr', models.CharField(default='', max_length=200, verbose_name='原始地址')),
            ],
            options={
                'verbose_name_plural': '章节',
                'db_table': 'comic_chapter',
                'ordering': ['order', '-update_at'],
                'permissions': (('comic_chapter_add', '添加漫画章节'), ('comic_chapter_edit', '编辑漫画章节'), ('comic_chapter_detail', '查看漫画章节'), ('comic_chapter_delete', '删除漫画章节')),
            },
            managers=[
                ('normal', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ChapterImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='normal', max_length=10)),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('comic_id', models.IntegerField(default=0, verbose_name='漫画ID')),
                ('chapter_id', models.IntegerField(default=0, verbose_name='章节ID')),
                ('image_id', models.IntegerField(default=0, null=True, verbose_name='图片ID')),
                ('order', models.IntegerField(default=0, verbose_name='排序位置')),
                ('active', models.BooleanField(default=True, verbose_name='生效')),
            ],
            options={
                'verbose_name_plural': '章节详情',
            },
            managers=[
                ('normal', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='CoverImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='normal', max_length=10)),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('comic_id', models.IntegerField(default=0, verbose_name='漫画ID')),
                ('book_id', models.IntegerField(default=0, verbose_name='小说ID')),
                ('chapter_id', models.IntegerField(default=0, verbose_name='章节ID')),
                ('image_id', models.IntegerField(default=0, null=True, verbose_name='图片ID')),
                ('order', models.IntegerField(default=0, verbose_name='排序位置')),
                ('active', models.BooleanField(default=True, verbose_name='生效')),
            ],
            options={
                'verbose_name_plural': '封面',
            },
            managers=[
                ('normal', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='normal', max_length=10)),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('img_type', models.CharField(choices=[('0', '漫画封面'), ('3', '小说封面'), ('1', '章节封面'), ('2', '章节内容')], default='', max_length=30, null=True, verbose_name='图片类型')),
                ('order', models.IntegerField(default=0, verbose_name='排序位置')),
                ('active', models.BooleanField(default=True, verbose_name='生效')),
                ('name', models.CharField(default='', max_length=255, verbose_name='名称')),
                ('key', models.CharField(default='', max_length=50, verbose_name='图片ID KEY')),
            ],
            options={
                'verbose_name_plural': '图片',
                'db_table': 'comic_image',
                'ordering': ['order'],
            },
            managers=[
                ('normal', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='IndexBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='normal', max_length=10)),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('active', models.BooleanField(default=True, verbose_name='生效')),
                ('block_type', models.CharField(choices=[('COMIC', '漫画'), ('BOOK', '小说')], default='COMIC', max_length=10, verbose_name='模块类型')),
                ('desc_type', models.CharField(choices=[('CA', '轮播图'), ('PL', '图片在左'), ('PT', '图片在上')], default='CA', max_length=10, verbose_name='模块类型')),
                ('content_id', models.IntegerField(default=0, verbose_name='内容ID')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('normal', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Comic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='normal', max_length=10)),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.CharField(default='', max_length=60, unique=True, verbose_name='漫画名称')),
                ('collection_num', models.IntegerField(default=0, null=True, verbose_name='收藏数量')),
                ('click_num', models.IntegerField(default=0, null=True, verbose_name='点击数量')),
                ('desc', models.CharField(default='', max_length=500, verbose_name='描述')),
                ('markup', models.CharField(default='', max_length=100, null=True, verbose_name='标签')),
                ('on_shelf', models.BooleanField(default=True, verbose_name='是否上架')),
                ('is_finished', models.BooleanField(default=False, verbose_name='是否能已完结')),
                ('latest_chapter', models.CharField(default='', max_length=20, verbose_name='最新章节')),
                ('origin_addr', models.CharField(default='', max_length=200, verbose_name='原始地址')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='comic_admin.Author')),
            ],
            options={
                'verbose_name_plural': '漫画',
                'db_table': 'comic',
                'ordering': ['-update_at'],
                'permissions': (('comic_add', '添加漫画'), ('comic_edit', '编辑漫画'), ('comic_detail', '查看漫画'), ('comic_delete', '删除漫画')),
            },
            managers=[
                ('normal', django.db.models.manager.Manager()),
            ],
        ),
    ]
