# Generated by Django 2.1.2 on 2018-12-26 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comic_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexblock',
            name='active',
            field=models.BooleanField(default=True, verbose_name='生效'),
        ),
    ]
