# Generated by Django 2.1.3 on 2018-12-07 13:41

from django.db import migrations, models
import django.db.models.manager
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('comic_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='normal', max_length=10)),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('block_type', models.CharField(choices=[('COMIC', '漫画'), ('BOOK', '小说')], default='COMIC', max_length=10, verbose_name='模块类型')),
                ('desc_type', models.CharField(choices=[('CA', '轮播图'), ('PL', '图片在左'), ('PT', '图片在上')], default='CA', max_length=10, verbose_name='模块类型')),
                ('content_id', models.IntegerField(default=0, verbose_name='内容ID')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('normal', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ['order', '-update_at'], 'permissions': (('comic_chapter_add', '添加漫画章节'), ('comic_chapter_edit', '编辑漫画章节'), ('comic_chapter_detail', '查看漫画章节'), ('comic_chapter_delete', '删除漫画章节')), 'verbose_name_plural': '章节'},
        ),
        migrations.AddField(
            model_name='coverimage',
            name='book_id',
            field=models.IntegerField(default=0, verbose_name='小说ID'),
        ),
        migrations.AlterField(
            model_name='image',
            name='img_type',
            field=models.CharField(choices=[('0', '漫画封面'), ('3', '小说封面'), ('1', '章节封面'), ('2', '章节内容')], default='', max_length=2, null=True, verbose_name='图片类型'),
        ),
    ]
