# Generated by Django 2.1.2 on 2018-11-01 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comic_admin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='cover_image',
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='detail_image',
        ),
        migrations.RemoveField(
            model_name='chapterimage',
            name='img_id',
        ),
        migrations.RemoveField(
            model_name='comic',
            name='cover_image',
        ),
        migrations.RemoveField(
            model_name='coverimage',
            name='img_id',
        ),
        migrations.AddField(
            model_name='chapterimage',
            name='active',
            field=models.BooleanField(default=True, verbose_name='生效'),
        ),
        migrations.AddField(
            model_name='chapterimage',
            name='img_key',
            field=models.ForeignKey(default=0, limit_choices_to={'img_type': '2'}, on_delete=django.db.models.deletion.DO_NOTHING, to='comic_admin.Image', to_field='key'),
        ),
        migrations.AddField(
            model_name='chapterimage',
            name='order',
            field=models.IntegerField(default=0, verbose_name='排序位置'),
        ),
        migrations.AddField(
            model_name='coverimage',
            name='active',
            field=models.BooleanField(default=True, verbose_name='生效'),
        ),
        migrations.AddField(
            model_name='coverimage',
            name='img_key',
            field=models.ForeignKey(default=0, limit_choices_to={'img_type__in': ['1', '0']}, on_delete=django.db.models.deletion.DO_NOTHING, to='comic_admin.Image', to_field='key'),
        ),
        migrations.AddField(
            model_name='coverimage',
            name='order',
            field=models.IntegerField(default=0, verbose_name='排序位置'),
        ),
        migrations.AlterField(
            model_name='coverimage',
            name='chapter_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='comic_admin.Chapter'),
        ),
    ]
