# Generated by Django 3.0.4 on 2020-03-15 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comic_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='img_type',
            field=models.CharField(choices=[('0', '漫画封面'), ('3', '小说封面'), ('1', '章节封面'), ('2', '章节内容')], default='', max_length=30, null=True, verbose_name='图片类型'),
        ),
        migrations.AlterField(
            model_name='image',
            name='key',
            field=models.CharField(default='', max_length=50, verbose_name='图片ID KEY'),
        ),
    ]
