# Generated by Django 2.1.2 on 2018-11-22 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comic_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='gender',
            field=models.CharField(choices=[('M', '男'), ('F', '女'), ('A', '未知')], default='A', max_length=2, verbose_name='性别'),
        ),
    ]
