# Generated by Django 2.1.2 on 2018-10-31 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comic_admin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='cover_img_id',
        ),
        migrations.AlterField(
            model_name='chapterimage',
            name='chapter_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='comic_admin.Chapter'),
        ),
        migrations.AlterField(
            model_name='chapterimage',
            name='comic_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='comic_admin.Comic'),
        ),
        migrations.AlterField(
            model_name='chapterimage',
            name='img_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='comic_admin.Image'),
        ),
        migrations.AlterField(
            model_name='coverimage',
            name='comic_id',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='comic_admin.Comic'),
        ),
        migrations.AlterField(
            model_name='coverimage',
            name='img_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='comic_admin.Image'),
        ),
    ]
