# Generated by Django 2.1.2 on 2018-11-23 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comic_admin', '0002_author_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='comic',
        ),
        migrations.RemoveField(
            model_name='chapterimage',
            name='chapter',
        ),
        migrations.RemoveField(
            model_name='chapterimage',
            name='comic',
        ),
        migrations.AddField(
            model_name='chapter',
            name='comic_id',
            field=models.IntegerField(default=0, verbose_name='漫画ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chapterimage',
            name='chapter_id',
            field=models.IntegerField(default=0, verbose_name='章节ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chapterimage',
            name='comic_id',
            field=models.IntegerField(default=0, verbose_name='漫画ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chapterimage',
            name='image',
            field=models.IntegerField(default=0, null=True, verbose_name='图片ID'),
        ),
    ]
