# Generated by Django 2.1.2 on 2018-10-31 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comic_admin', '0002_auto_20181031_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(default=0, upload_to='photos/%Y/%m/%d', verbose_name='图片'),
            preserve_default=False,
        ),
    ]
