# Generated by Django 2.1.2 on 2018-11-29 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comic_admin', '0002_auto_20181129_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexblock',
            name='block_type',
            field=models.CharField(choices=[('Comic', '漫画'), ('Book', '小说')], default='comic', max_length=10, verbose_name='模块类型'),
        ),
    ]
