# Generated by Django 2.1.2 on 2018-10-31 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comic_admin', '0003_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(default='', upload_to='photos/%Y/%m/%d', verbose_name='图片'),
        ),
    ]
