# Generated by Django 2.1.2 on 2018-10-31 11:10

import comic_web.utils.photo
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comic_admin', '0004_auto_20181031_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image',
        ),
        migrations.AlterField(
            model_name='image',
            name='key',
            field=models.ImageField(blank=True, upload_to=comic_web.utils.photo.django_image_upload_handler, verbose_name='图片'),
        ),
    ]
